anovos/anovos

src/main/anovos/data_analyzer/quality_checker.py, src/main/anovos/data_analyzer/stats_generator.py, src/main/anovos/data_report/basic_report_generation.py, src/main/anovos/data_report/report_generation.py
1. duplicate_detection:
- Added number of duplicate rows and percentage of duplicate rows for to print
2. IDness_detection:
- If treatment is true,  the column name 'flagged' will be renamed as 'treated'
3. biasedness_detection:
- also added 'mode_rows' to select as part of odf_print (Note: Also changed to add 'mode_rows' correspondingly in measures_of_centralTendency.)
- If treatment is true,  the column name 'flagged' will be renamed as 'treated'
4. Corresponding changes in report_generation
5. outlier_detection changed new line formatting as there was a stray print "skewed_cols))"
=> changes for easy api integration changes

src/main/anovos/data_report/basic_report_generation.py
Duplicate of https://github.com/anovos/anovos/pull/24
But recreating as previous merge was removed
=> basic report optimized with presaved statistics

src/main/anovos/data_analyzer/quality_checker.py, src/main/anovos/data_transformer/transformers.py
The following functional changes have been made to quality_checker module 
In 
`nullRows_detection`  - commit e90e97b0fb5801c7e4c8b0448f3f609a9bcb2f94
1. changed column flagged to treated in case of treatment has been done
`nullColumns_detection` - commit 25480f2885a9a26594ebc96874e0dc10b88e2813
1. added treatment threshold support for all treatment methods if available (it is still only mandatory for column_removal)
`imputation_MMM` - commit fe00f971421bc6646ef2918991cc6169468b87af
1. added 'mode' imputation for numerical columns as well
`invalidEntries_detection` - commit 0c0201a29e3b3a121e8441eccfa58fd1d89cbb0d
1. added arguments - `treatment_method`, `treatment_configs`, `stats_missing`, `stats_unique`, `stats_mode`
2. added support for different treatment_methods - `null_replacement` …
=> Quality checker - functional changes

README.md
=> updated typo in README

src/test/anovos/data_analyzer/test_quality_checker.py, src/test/anovos/data_analyzer/test_stats_generator.py
1. changes in unit testing for baseness, IDness and duplicate_detection as part of #23 
2. changes in global_summary (removed an inconsistent assert statement)
=> Unit test changes for #31

src/main/anovos/data_ingest/data_ingest.py, src/test/anovos/data_ingest/test_data_ingest.py
added an optional argument - 'column_order' in 'write_dataset' method - to specify sequence of columns while writing out data frame.
=> changes in data_ingest (write_dataset)

README.md
made some changes on readme to reflect the recent changes
=> Docker related readme

src/main/anovos/data_analyzer/ts_analyzer.py, src/main/anovos/data_ingest/ts_auto_detection.py, src/main/anovos/shared/utils.py
Added databricks condition in time_series scripts
=> Ts databricks change

README.md, setup.py
Updating README and setup for 0.2.1 release
=> Release 021 update

src/main/anovos/data_ingest/data_ingest.py
Added error check for join function 
1. if specified data frames do not have joining column
2. if specified data frames have duplicate non joining columns
=> Data ingest error check

src/main/anovos/data_ingest/data_ingest.py
@kajanansangar 
Missed one check for single or multiple join columns. Added now
=> changed error check to also satisfy multiple join columns

src/main/anovos/data_report/report_generation.py
The input data to Pie Chart was not being read properly which was causing it to not populate the chart labels, etc. The latest change addresses the same.
=> Fixing the Pie Chart Issue

setup.py
Update Setup for v0.3.0 release
=> Update Setup for v0.3.0

.github/workflows/push_to_branch.yml
This should fix #221
cf. https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull-request-events-for-forked-repositories
=> Run push_to_branch workflow on PR events

.github/workflows/anovos-notebook.yml, examples/anovos_notebook/build_image.sh
https://github.com/jupyter/docker-stacks/issues/1756 should have been resolved with https://github.com/jupyter/docker-stacks/pull/1757
=> Return to latest docker-stacks images for notebook/examples builds after upstream fix

Dockerfile
It seems that this file was mistakenly replaced
=> Revert Dockerfile for running tests locally to previous version

tutorial/changelog/README.md
updated docker image v3 and latest tags
=> changes to docker image updated in changelog

src/main/anovos/data_report/basic_report_generation.py
minor update done on the header name
=> basic report header update

bin/aws_bootstrap_files/README.md, bin/aws_bootstrap_files/setup_on_aws_emr_5_30_and_above_latest_release_version.sh
Added sh file for directly installing anovos for latest released version and modified README accordingly
=> added sh file for directly installing anovos and modified README

demo/Dockerfile
1. changes spark tgz mirror to an public path from s3 
2. modified demo docker image Dockerfile
=> changes to spark mirror
